In [6]:
import numpy as np
#1. arange
a=np.arange(1,10+1)
b=np.arange(0.5,5+1,0.25)
print("1-10:",a)
print("0.5-5:",b)

1-10: [ 1  2  3  4  5  6  7  8  9 10]
0.5-5: [0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.   5.25 5.5  5.75]


In [10]:
# 2.zeros
a=np.zeros(10,dtype=int)
b=np.zeros((3,4),dtype=int)
print("10 zeros:",a)
print("matrix 3x4, 12 zeros:",b)

10 zeros: [0 0 0 0 0 0 0 0 0 0]
matrix 3x4, 12 zeros: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [14]:
#3.linespace
a=np.linspace(2,12,5,dtype=int)
b=np.linspace(3,9,4,dtype=int)
print("2-12:",a)
print("3-9:",b)


2-12: [ 2  4  7  9 12]
3-9: [3 5 7 9]


In [40]:
#4.random
a=np.random.rand(4,2)
b=np.random.randint(10,20,(3,3))
c=np.reshape(a,8)# must be the same legth of the origin array
print("matrix 4x2 (0-.99999):",a)
print("matrix 3x3 (10,20):",b)
print("reshape matrix 3x4 (0,0.99999):",c)

matrix 4x2 (0-.99999): [[0.82346066 0.11898955]
 [0.488693   0.88704883]
 [0.60442805 0.56251028]
 [0.12563725 0.41020409]]
matrix 3x3 (10,20): [[10 18 10]
 [11 15 17]
 [17 17 11]]
reshape matrix 3x4 (0,0.99999): [0.82346066 0.11898955 0.488693   0.88704883 0.60442805 0.56251028
 0.12563725 0.41020409]


In [ ]:
# using seed function, allow th control the initial random function
# will to receive the same results as the previous executions
# used for simulations and testing when using random functions.