In [11]:
import numpy as np
np.absolute(-3)

3

In [59]:
first_np_arr=np.array([1.11,2.987654,3],dtype=int)
second=[4,5,6]
print(first_np_arr)
print(first_np_arr+second)
third=first_np_arr+second
print(third)
matrix_arr=np.array([[1,2,3],[4,5,6]])
print(matrix_arr)
print(type(matrix_arr))
line_space=np.linspace(0,10,4)
print(line_space)

[1 2 3]
[5 7 9]
[5 7 9]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[ 0.          3.33333333  6.66666667 10.        ]


In [105]:
a=np.random.rand(2)*9
print(type(a))
print(a)
b=np.round(np.random.rand(2),2)
print(b)
c=np.random.randint(0,10,2)
print(c)

<class 'numpy.ndarray'>
[3.3861934  1.38774175]
[0.71 0.72]
[5 8]


In [107]:
np.random.seed(42)
np.random.randint(0,101,(2,5))

array([[51, 92, 14, 71, 60],
       [20, 82, 86, 74, 74]])